* BraviShell Installer

This repository contains a bootstrap python script which will install a full
BraviShell development environment on your system.

* Access
You'll need to be a collaborator to do this. You should know who to email about this
already!

* Requirements
This installer has only been tested on MacOS 10.10---10.13 running Matlab 2017a+.
Other configurations may work, but are not guaranteed.

MacOS Mojave, and some very modern MacBooks, may not work properly with the openGL
tests as current written.

The =git= version control system must be installed and be relatively modern (2.0+)

* Use

** Installation
To install in one shot, copy and paste the entire snippet below into a terminal and
hit enter.
#+begin_src bash
curl -OLs https://raw.githubusercontent.com/BraviShell/bravishell-installer/master/install_bravishell.py && \
python install_bravishell.py && \
rm install_bravishell.py
#+end_src

To do this manually, in a terminal session do the following: 

#+begin_src bash
git clone https://github.com/BraviShell/bravishell-installer
cd bravishell-installer
python install_bravishell.py
#+end_src

** Launching BraviShell

Once installed, open MATLAB and navigate to the location you installed BraviShell to in the matlab file browser. 

Then, run =setup.m=. 
Then, type =BraviShell= at the command prompt.  Select the "Development" version. 
Then, type =BraviShell= again, and BraviShell should run.
